### ISSUE TITLE
Release `auth-clients` packages as 1.0

### ISSUE THREAD

**Issue by mattbjordan** [iTwin/auth-clients#102]
```[tasklist]
### Package Releases
- [x] Release @itwin/browser-authorization as 1.0
- [x] Release @itwin/node-cli-authorizationas 1.0
- [x] Release @itwin/service-authorization as 1.0
- [x] Release @itwin/oidc-signin-tool as 4.0
```

```[tasklist]
### Tasks
- [x] https://github.com/iTwin/auth-clients/issues/84
- [ ] https://github.com/iTwin/auth-clients/issues/101
- [ ] https://github.com/iTwin/auth-clients/issues/103
- [ ] https://github.com/iTwin/auth-clients/issues/92
- [ ] https://github.com/iTwin/auth-clients/issues/106
- [ ] https://github.com/iTwin/auth-clients/issues/105
- [ ] https://github.com/iTwin/auth-clients/issues/149
- [x] Cleanup release tags
- [x] Review all exports
- [x] Release each package as 1.0
- [ ] https://github.com/iTwin/auth-clients/issues/148
- [ ] https://github.com/iTwin/auth-clients/issues/113
- [ ] https://github.com/iTwin/auth-clients/issues/108
- [ ] https://github.com/iTwin/auth-clients/issues/137
- [ ] https://github.com/iTwin/auth-clients/issues/151
```

**Comment by GytisCepk** [comment]
@aruniverse , I'm guessing, we want to drop Node 12-16 and Electron 15-22 here as well before releasing 1.0 ?

This would block release at least till Feb. 7 (planned release date of Electron 23).

**Comment by aruniverse** [comment]
I'd like to discuss electron auth more with the desktop teams. I think this PKG will most likely be one of the later releases in the quarter

**Comment by karolis-zukauskas** [comment]
See #113 before doing a release

**Comment by ben-polinsky** [comment]
Thanks darn

**Comment by ben-polinsky** [comment]
Thought I could close a referenced issue without closing this but not the case.
